.github/workflows/deployment-images.yaml
.github/workflows/elixir-build-check.yaml

[Card](https://rentpath.atlassian.net/browse/SRV-3862)

GitHub Reusable Workflows for Elixir

---

.github/workflows/ruby-build-check.yml

[Story](https://rentpath.atlassian.net/browse/SRV-4034)

Added ruby build check flow

---

.github/workflows/deployment-images.yaml
.github/workflows/elixir-build-check.yaml

[Card](https://rentpath.atlassian.net/browse/SRV-4852)

Update to new set-output syntax

---

.github/workflows/deployment-images.yaml

[Card](https://rentpath.atlassian.net/browse/SRV-4904)

Remove GHCR_USER_PAT build arg from deployment-images workflow

---

.github/workflows/clj-build-app.yml
.github/workflows/clj-build-lib.yml
.github/workflows/clj-build.yml

[Card](https://rentpath.atlassian.net/browse/SRV-5153)

Creating a reusable build workflow for clojure libs

---

.github/workflows/clj-build-lib.yml

[Card](https://rentpath.atlassian.net/browse/SRV-5153)

Fixing remaning token used by clojure lib build workflow

---

.github/workflows/elixir-build-check.yaml

[Card](https://rentgroup.atlassian.net/browse/SRV-5068)

Add compile-connected to xref check

---

.github/workflows/elixir-build-check.yaml

[Card](https://rentgroup.atlassian.net/browse/SRV-6199)

Update elixir-build-check workflow's Mix Format to ignore deleted files

---

.github/workflows/clj-build-lib.yml
.github/workflows/clj-build-test-img.yml
.github/workflows/clj-build.yml

[Card](https://rentgroup.atlassian.net/browse/SRV-6306)

Update clj build workflows to use updated actions using Node20 instead of Node16

---

.github/workflows/clj-build.yml

[CARD](https://rentgroup.atlassian.net/browse/DX-4269)

feat: use official docker action

---

.github/workflows/clj-build.yml

[CARD](https://rentgroup.atlassian.net/browse/DX-4269)

fix: pass in token from org

---

.github/workflows/clj-build.yml

[CARD](https://rentgroup.atlassian.net/browse/DX-4269)

fix: correctly reference tagging step

---

.github/workflows/clj-build.yml

[CARD](https://rentgroup.atlassian.net/browse/DX-4269)

fix: correct typo

---

.github/workflows/clj-build.yml

[Card](https://rentgroup.atlassian.net/browse/SRV-6317)

Update recently introduced github action docker/build-push-action

---

.github/workflows/deployment-images.yaml
.github/workflows/elixir-build-check.yaml

[CARD](https://rentgroup.atlassian.net/browse/DX-4166)

chore: replace workflow permissions token with rossum token

---

.github/workflows/create-tag-from-mix-version.yaml

[CARD](https://rentgroup.atlassian.net/browse/DX-4166)

chore: use Github app installation secrets to generate token

---

.github/workflows/clj-build-lib.yml

[card](https://rentgroup.atlassian.net/browse/SRV-6670)

Bump builder image to one based on Temurin17

---

.github/workflows/elixir-build-check.yaml

[card](https://rentgroup.atlassian.net/browse/SRV-6901)

Use actions-services-elixir-deps@v2

---

.github/workflows/elixir-build-check.yaml

[card](https://rentgroup.atlassian.net/browse/SRV-6901)

More GH action version bumps

---

.github/workflows/create-tag-from-mix-version.yaml
.github/workflows/deployment-images.yaml

[card](https://rentgroup.atlassian.net/browse/SRV-6901)

Updating other elixir workflows

---

.github/workflows/deployment-images.yaml

[CARD](https://redfin.atlassian.net/browse/DX-5222)

feat: update deplyoment-images workflow to push to rent-corp ghcr

---

.github/workflows/deployment-images.yaml

[CARD](https://redfin.atlassian.net/browse/DX-5250)

fix: also push test images to arbitrary registry

---

.github/workflows/deployment-images.yaml

[CARD](https://redfin.atlassian.net/browse/DX-5250)

fix: close quotations
